language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0
gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-3.2.x
  - gemfiles/Gemfile.rails-4.0.x
  - gemfiles/Gemfile.rails-4.1.x

matrix:
  exclude:
    # has test/unit/testcase removed, and also 3.2.x is too old to support
    # ruby 2.2.0. so ignoring this combination.
    - rvm: 2.2.0
      gemfile: gemfiles/Gemfile.rails-3.2.x

script:
  - bundle exec rake --trace
