name: Invoicing
url: http://example.org
description: Ruby Invoicing Framework

permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
